foreground         #fafafa
background         #030303
cursor             #fafafa
active_tab_foreground     #030303
active_tab_background     #fafafa
inactive_tab_foreground   #fafafa
inactive_tab_background   #030303
active_border_color   #fafafa
inactive_border_color #030303
bell_border_color     #7c7c7c
color0       #030303
color8       #585858
color1       #7c7c7c
color9       #7c7c7c
color2       #848484
color10      #848484
color3       #8c8c8c
color11      #8c8c8c
color4       #8d8d8d
color12      #8d8d8d
color5       #f6f6f6
color13      #f6f6f6
color6       #cecece
color14      #cecece
color7       #fafafa
color15      #fafafa
