foreground            #f0dedd
background            #1a1111
selection_foreground  #f0dedd
selection_background  #524343
url_color             #ffb3b2
cursor                #f0dedd
cursor_text_color     #1a1111

color0  #1a1111
color8  #524343

color1  #ffb4ab
color9  #ffb4ab

color2  #ffb3b2
color10 #ffb3b2

color3  #e4c18d
color11 #e4c18d

color4  #e6bdbb
color12 #e6bdbb

color5  #a08c8b
color13 #a08c8b

color6  #904a4a
color14 #904a4a

color7  #f0dedd
color15 #d7c1c0

