color0 #151313
color1 #ffb4ab
color2 #d6c2c5
color3 #cfc4c5
color4 #d1c5b4
color5 #d6c2c5
color6 #cfc4c5
color7 #e7e1e1
color8 #9a8e8f
color9 #ffb4ab
color10 #d6c2c5
color11 #cfc4c5
color12 #d1c5b4
color13 #d6c2c5
color14 #cfc4c5
color15 #e7e1e1

cursor                #e7e1e1
cursor_text_color     #151313
background            #151313
foreground            #e7e1e1
selection_foreground  #d1c3c5
selection_background  #4e4446
active_border_color   #d6c2c5
inactive_border_color #4e4446
url_color             #d6c2c5
