
if status is-interactive
    set -g fish_greeting
    starship init fish | source
    set -gx SUDO_EDITOR "subl -w"


function wal-smart
    if test (count $argv) -eq 0
        return 1
    end
    set img_path (realpath "$argv[1]")
    walrs -i "$img_path"
    while not test -f ~/.cache/wal/colors.sh
        sleep 0.05
    end
    sleep 0.1
    cp ~/.cache/wal/colors-waybar.css ~/.config/waybar/colors/wal.css
    sed -i "s|exec-once = walrs -n -i.*|exec-once = walrs -n -i $img_path|" ~/.config/hypr/hyprland.conf
    sed -i "s|exec-once = awww img.*|exec-once = awww img \"$img_path\" --transition-type none|" ~/.config/hypr/hyprland.conf~/.config/hypr/hyprland.conf
    if not pgrep -x awww-daemon >/dev/null
        awww-daemon &
        sleep 0.5
    end
    awww img "$img_path" --transition-type random --transition-step 90 --transition-fps 60
    if test -f ~/.cache/wal/sequences
        if pgrep -x kitty >/dev/null
            cat ~/.cache/wal/sequences
        end
    end
    set color5 (grep "color5='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set color8 (grep "color8='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    if test -n "$color5"
        printf "general {\n    col.active_border = rgb(%s)\n    col.inactive_border = rgb(%s)\n}\n" \
            $color5 $color8 > ~/.config/hypr/colors.conf
        hyprctl reload >/dev/null 2>&1 &
    end
    pkill waybar
    waybar >/dev/null 2>&1 &
    pkill swaync
    sleep 0.3
    swaync >/dev/null 2>&1 &
    # --- HYPRLOCK ---
    mkdir -p ~/.config/hypr/wallpapers
    ln -sf "$img_path" ~/.config/hypr/wallpapers/lockscreen.jpg
    # --- WLOGOUT COLORS ---
    mkdir -p ~/.config/wlogout
    set bg (grep "background='" ~/.cache/wal/colors.sh | cut -d"'" -f2)
    set c5 (grep "color5='" ~/.cache/wal/colors.sh | cut -d"'" -f2)
    set c7 (grep "color7='" ~/.cache/wal/colors.sh | cut -d"'" -f2)
    set c8 (grep "color8='" ~/.cache/wal/colors.sh | cut -d"'" -f2)
    printf "/* autogenerated by wal */\n\
@define-color bg rgba(3, 3, 3, 0.85);\n\
@define-color button-bg %s;\n\
@define-color button-border %s;\n\
@define-color text %s;\n\
\n\
@define-color hover-bg %s;\n\
@define-color hover-border %s;\n\
@define-color hover-text #ffffff;\n\
\n\
@define-color active-bg %s;\n\
@define-color active-border %s;\n\
@define-color active-text #ffffff;\n" \
        $bg $c8 $c7 \
        $c5 $c7 \
        $c7 $c5 \
        > ~/.config/wlogout/colors.css
    # --- WLOGOUT ICON RECOLOR ---
    set icon_color $c5
    for icon in lock shutdown reboot suspend
        magick ~/.config/wlogout/icons/$icon.png \
            -alpha on -fill "$icon_color" -colorize 100% \
            ~/.config/wlogout/icons/$icon.png
    end
    # --- KITTY COLORS ---
    if not pgrep -x mango >/dev/null
        # только в Hyprland — применяем walrs цвета для kitty
        if test -f ~/.cache/wal/sequences
            if pgrep -x kitty >/dev/null
                cat ~/.cache/wal/sequences
            end
        end
    end

end



function rofi-wallpaper
    set wall_dir ~/wallpapers
    set selected (ls $wall_dir | while read -l img
        echo -en "$img\0icon\x1f$wall_dir/$img\n"
    end | rofi -dmenu -i -p "Wallpapers" -show-icons -theme-str 'listview { columns: 3; lines: 3; } element { orientation: vertical; } element-icon { size: 120px; }')

    if test -n "$selected"
        wal-smart "$wall_dir/$selected"
    end
end


# Быстрые команды для управления zapret
alias zapret-config="$HOME/zapret-configs/install.sh"
alias zapret-utils="$HOME/zapret-configs/utils-zapret.sh"

# Пути
fish_add_path /home/vdaseuu/.local/bin
end
